### ISSUE TITLE
Airdrop is locked too

### ISSUE THREAD

**Issue by Tortellio** [cartman-2000/AntiGrief#2]
the makecontainerslocked also make airdrop/carepackage crate locked

**Comment by cartman-2000** [comment]
Could you add ID 1374 to the SkipElementIDs list?

**Comment by Tortellio** [comment]
ok thanks

**Comment by cartman-2000** [comment]
I did upload a build of the plugin that disallows the locking of the airdrop container when global container lock is enabled. It's not required to update to this build of the plugin, if you have the element id in the SkipElementIDs list.

https://github.com/cartman-2000/AntiGrief/releases/tag/1.4.5.1
